# Generated by Django 4.1.4 on 2022-12-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sport_equipment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="is_own_shop",
            field=models.BooleanField(default=False),
        ),
    ]
