# Generated by Django 4.1.4 on 2023-01-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sport_equipment', '0005_categorycard_delete_productcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='tags',
            field=models.ManyToManyField(to='sport_equipment.tag'),
        ),
    ]
