# Generated by Django 4.1.4 on 2023-01-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sport_equipment', '0006_tag_equipment_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorycard',
            old_name='product',
            new_name='category',
        ),
    ]
